name: Terminus Test

on: [push]

jobs:
  delete-multidev:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@debug
      with:
        disable-cache: true
        debug: true
    - name: Print System Details
      run: |
        php -v
        uname -a
        terminus --version

